version: '3'

services:
  auth-service:
    image: akb25/auth-service:latest
    container_name: auth-service
    ports:
      - "4000:4000"
    env_file:
      - ./services/auth-service/.env
    networks:
      - app-net


  course-service:
    image: akb25/course-service:latest
    container_name: course-service
    ports:
      - "4001:4001"
    env_file:
      - ./services/course-service/.env
    networks:
      - app-net

  
  progress-service:
    image: akb25/progress-service:latest
    container_name: progress-service
    ports:
      - "4002:4002"
    env_file:
      - ./services/progress-service/.env
    networks:
      - app-net


  analytics-service:
    image: akb25/analytics-service:latest
    container_name: analytics-service
    ports:
      - "4003:4003"
    env_file:
      - ./services/analytics-service/.env
    networks:
      - app-net


  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - course-service
      - progress-service
      - analytics-service
    networks:
      - app-net

networks:
  app-net: