version: '3.8'

services:
  progress-service:
    build: .
    container_name: progress-service
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules