name: Deploy course service

on:
  push:
    paths:
      - 'services/course-service/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install deps
      run: npm install
      working-directory: ./services/course-service

    # - name: Run tests
    #   run: npm test
    #   working-directory: ./auth-service

    - name: Docker Build & Push
      run: |
        docker build -t akb25/course-service:latest .
        docker push akb25/course-service:latest
      working-directory: ./services/course-service